USE menu_db;

INSERT INTO users (first_name, createdAt, updatedAt) VALUES ('Bobby', now(), now());
INSERT INTO users (first_name, createdAt, updatedAt) VALUES ('Melanie', now(), now());
INSERT INTO users (first_name, createdAt, updatedAt) VALUES ('McKell', now(), now());
INSERT INTO users (first_name, createdAt, updatedAt) VALUES ('Mark', now(), now());
INSERT INTO users (first_name, createdAt, updatedAt) VALUES ('Aaron', now(), now());
INSERT INTO restaurants (name, userId, createdAt, updatedAt) VALUES ("Bob's Burgers", 1, now(), now());
INSERT INTO restaurants (name, userId, createdAt, updatedAt) VALUES ("Mel's Muffalettas", 2, now(), now());
INSERT INTO restaurants (name, userId, createdAt, updatedAt) VALUES ("McKell's Macaroons", 3, now(), now());
INSERT INTO restaurants (name, userId, createdAt, updatedAt) VALUES ("Mark's Muffins", 4, now(), now());
INSERT INTO restaurants (name, userId, createdAt, updatedAt) VALUES ("Aaron's Apples", 5, now(), now());
INSERT INTO menus (name, restaurantId, createdAt, updatedAt) VALUES ('Lunch', 1, now(), now());
INSERT INTO menus (name, restaurantId, createdAt, updatedAt) VALUES ('Lunch', 2, now(), now());
INSERT INTO menus (name, restaurantId, createdAt, updatedAt) VALUES ('Breakfast', 3, now(), now());
INSERT INTO menus (name, restaurantId, createdAt, updatedAt) VALUES ('Breakfast', 4, now(), now());
INSERT INTO menus (name, restaurantId, createdAt, updatedAt) VALUES ('Breakfast', 5, now(), now());
INSERT INTO menus (name, restaurantId, createdAt, updatedAt) VALUES ('Dinner', 1, now(), now());
INSERT INTO menus (name, restaurantId, createdAt, updatedAt) VALUES ('Dinner', 2, now(), now());
INSERT INTO menus (name, restaurantId, createdAt, updatedAt) VALUES ('Lunch', 3, now(), now());
INSERT INTO menus (name, restaurantId, createdAt, updatedAt) VALUES ('Lunch', 4, now(), now());
INSERT INTO menus (name, restaurantId, createdAt, updatedAt) VALUES ('Lunch', 5, now(), now());
INSERT INTO menu_items (name, menuId, createdAt, updatedAt) VALUES ('Double Cheeseburger', 1, now(), now());
INSERT INTO menu_items (name, menuId, createdAt, updatedAt) VALUES ('Classic Muffaletta', 2, now(), now());
INSERT INTO menu_items (name, menuId, createdAt, updatedAt) VALUES ('Chocolate Macaroon', 3, now(), now());
INSERT INTO menu_items (name, menuId, createdAt, updatedAt) VALUES ('Blueberry Muffin', 4, now(), now());
INSERT INTO menu_items (name, menuId, createdAt, updatedAt) VALUES ('Apple Pie', 5, now(), now());
INSERT INTO menu_items (name, menuId, createdAt, updatedAt) VALUES ('Bacon Cheeseburger', 6, now(), now());
INSERT INTO menu_items (name, menuId, createdAt, updatedAt) VALUES ('Fancy Muffaletta', 7, now(), now());
INSERT INTO menu_items (name, menuId, createdAt, updatedAt) VALUES ('Blackberry Macaroon', 8, now(), now());
INSERT INTO menu_items (name, menuId, createdAt, updatedAt) VALUES ('Lemon Glaze Muffin', 9, now(), now());
INSERT INTO menu_items (name, menuId, createdAt, updatedAt) VALUES ('Mixed Berry Pie', 10, now(), now());
