USE menu_db;

INSERT INTO users (first_name, createdAt, updatedAt) VALUES ('Bobby', now(), now());
INSERT INTO users (first_name, createdAt, updatedAt) VALUES ('Melanie', now(), now());
INSERT INTO users (first_name, createdAt, updatedAt) VALUES ('McKell', now(), now());
INSERT INTO users (first_name, createdAt, updatedAt) VALUES ('Mark', now(), now());
INSERT INTO users (first_name, createdAt, updatedAt) VALUES ('Aaron', now(), now());
INSERT INTO trucks (name, createdAt, updatedAt) VALUES ("Bob's Burgers", now(), now());
INSERT INTO trucks (name, createdAt, updatedAt) VALUES ("Mel's Muffalettas", now(), now());
INSERT INTO trucks (name, createdAt, updatedAt) VALUES ("McKell's Macaroons", now(), now());
INSERT INTO trucks (name, createdAt, updatedAt) VALUES ("Mark's Muffins", now(), now());
INSERT INTO trucks (name, createdAt, updatedAt) VALUES ("Aaron's Apples", now(), now());
INSERT INTO menu_items (name, truckId, price, createdAt, updatedAt) VALUES ('Double Cheeseburger', 1, 10.99, now(), now());
INSERT INTO menu_items (name, truckId, price, createdAt, updatedAt) VALUES ('Bacon Cheeseburger', 1, 2.99, now(), now());
INSERT INTO menu_items (name, truckId, price, createdAt, updatedAt) VALUES ('Classic Muffaletta', 2, 9.49, now(), now());
INSERT INTO menu_items (name, truckId, price, createdAt, updatedAt) VALUES ('Fancy Muffaletta', 2, 12.99, now(), now());
INSERT INTO menu_items (name, truckId, price, createdAt, updatedAt) VALUES ('Chocolate Macaroon', 3, 3.99, now(), now());
INSERT INTO menu_items (name, truckId, price, createdAt, updatedAt) VALUES ('Blackberry Macaroon', 3, 4.49, now(), now());
INSERT INTO menu_items (name, truckId, price, createdAt, updatedAt) VALUES ('Blueberry Muffin', 4, 4.49, now(), now());
INSERT INTO menu_items (name, truckId, price, createdAt, updatedAt) VALUES ('Lemon Glaze Muffin', 4, 5.49, now(), now());
INSERT INTO menu_items (name, truckId, price, createdAt, updatedAt) VALUES ('Apple Pie', 5, 14.99, now(), now());
INSERT INTO menu_items (name, truckId, price, createdAt, updatedAt) VALUES ('Mixed Berry Pie', 5, 16.99, now(), now());
